---
- name: Déploiement et configuration de WordPress
  hosts: wordpress_machine
  become: yes

  tasks:
    - name: Mise à jour de la liste des paquets
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Installer les paquets requis pour Apache (ou Nginx) et PHP
      apt:
        name: 
          - apache2    # ou nginx
          - php
          - libapache2-mod-php   # ou php-fpm pour Nginx
          - php-mysql
          - php-mysqli
          - php-curl
          - php-gd
          - php-mbstring
          - php-xml
          - php-xmlrpc
      when: ansible_os_family == 'Debian'

    - name: Activer Apache (ou Nginx) et PHP
      service:
        name: 
          - apache2   # ou nginx
          - php-fpm
        state: started
        enabled: yes

    - name: Télécharger le package WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress-latest.tar.gz

    - name: Extraire les fichiers WordPress
      unarchive:
        src: /tmp/wordpress-latest.tar.gz
        dest: /var/www/html
        remote_src: yes
        owner: www-data
        group: www-data

    - name: Copier le fichier de configuration wp-config.php
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: www-data
        group: www-data

    - name: Définir les permissions pour WordPress
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

  handlers:
    - name: Redémarrer Apache (ou Nginx) et PHP
      service:
        name: 
          - apache2   # ou nginx
          - php-fpm
        state: restarted
