---
- name: Mise à jour de la liste des paquets
  apt:
    update_cache: yes
  become: true

- name: Installer les paquets requis pour Apache (ou Nginx) et PHP
  apt:
    name: 
      - apache2               # ou nginx
      - php
      - libapache2-mod-php    # ou php-fpm pour Nginx
      # - php-mysql
      # - php-mysqli
      # - php-curl
      # - php-gd
      # - php-mbstring
      # - php-xml
      # - php-xmlrpc
      # - mariadb_client
    state: present
  become: true

- name: Activer Apache (ou Nginx) et PHP
  service:
    name: 
      - apache2   # ou nginx
      - php-fpm
    state: started
    enabled: yes

- name: Télécharger le package WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress-latest.tar.gz

- name: Extraire les fichiers WordPress
  unarchive:
    src: /tmp/wordpress-latest.tar.gz
    dest: /var/www/html
    remote_src: yes

- name: Définir les permissions pour WordPress
  file:
    path: /var/www/html/wordpress
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'

- name: Redémarrer Apache (ou Nginx) et PHP
  service:
    name: 
      - apache2   # ou nginx
      - php-fpm
    state: restarted
