---
- name: Déploiement et configuration de la base de données
  hosts: db-vm
  gather_facts: false
  become: true

  tasks:
    - name: Mise à jour de la liste des paquets
      apt:
        update_cache: yes
      become: true

    - name: Installer MariaDB et ses dépendances
      apt:
        name:
          - mariadb-server
          - python3-pymysql     # Module Python pour se connecter à MariaDB depuis Ansible
          - python3-pip         # Gestionnaire de package Python (pour installer le module PyMySQL)
          - python3-setuptools  # Pour pouvoir utiliser pip avec les modules Python installés par dpkg
        state: present
      become: true
    
    - name: Sécuriser l'installation de MariaDB
      mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        host_all: yes

    - name: Démarrer le service MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Créer une base de données pour WordPress
      mysql_db:
        name: "{{ wp_db_name }}" 
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Créer un utilisateur spécifique pour WordPress
      mysql_user:
        name: "{{ wp_db_user }}"          
        password: "{{ wp_db_password }}"  
        priv: "{{ wp_db_name }}.*:ALL"    # Accorde tous les privilèges sur la base de données WordPress
        host: "%"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"

    - name: Réinitialiser les privilèges MySQL
      mysql_user:
        name: ""
        password: ""  
        priv: "*.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mariadb_root_password }}"
      tags: mariadb

    - name: Activer les connexions depuis toutes les adresses
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: "^bind-address"
        line: "bind-address = 0.0.0.0"
        backup: yes
      notify:
        - Redémarrer mariadb
      tags: mariadb

  handlers:
    - name: Redémarrer MariaDB
      service:
        name: mariadb
        state: restarted
      become: true
