plugin: gcp_compute
zones:
  - europe-west9-a
projects:
  - pure-anthem-393513
service_account_file: /Users/joffreybena/Desktop/DevOps/TP-M2I/TP1/TP1-VM_WORDPRESS/credentials.json
auth_kind: serviceaccount
keyed_groups:
  - key: labels
    prefix: label
  - key: zone
    prefix: zone
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
