# Variables pour le déploiement et la configuration de la base de données
wp_admin_user: "root"
wp_admin_password: "root_password"

mariadb_root_password: "mot_de_passe_root_mariadb"

wp_db_name: "nom_de_la_base_de_donnees_wordpress"
wp_db_user: "utilisateur_wordpress"
wp_db_password: "mot_de_passe_utilisateur_wordpress"